services:
  - type: web
    name: auth-service
    runtime: docker
    dockerfilePath: ./backend/auth_service/Dockerfile
    dockerContext: ./backend/auth_service
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: content-service
    runtime: docker
    dockerfilePath: ./backend/content_service/Dockerfile
    dockerContext: ./backend/content_service
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: test-service
    runtime: docker
    dockerfilePath: ./backend/test_service/Dockerfile
    dockerContext: ./backend/test_service
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CONTENT_SERVICE_URL
        sync: false

  - type: web
    name: session-service
    runtime: docker
    dockerfilePath: ./backend/session_service/Dockerfile
    dockerContext: ./backend/session_service
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CONTENT_SERVICE_URL
        sync: false
      - key: TEST_SERVICE_URL
        sync: false
