services:
  - type: web
    name: testing-expert-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
